[package]
name = "winapps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
sevenz-rust={version="0.2", features=["zstd"]}
derive-new = "0.5"
home = "0.5"
indicatif = { version="0.17", features = ["tokio"] }
reqwest = { version = "0.12", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.11"
thiserror = "1.0"
tokio = { version = "1.37", features = ["full"] }
tokio-stream = "0.1"
tokio-util = {version="0.7", features=["io"]}
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
